config/routes.rb
Eventful::Application.routes.draw do
  get "eventful/home"
  get "eventful/next"
  get "eventful/test"

  root 'eventful#index'
  resources :pics

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :name, :start_time

	def start_time
		event_start_time
	end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/pic.rb
class Pic < ActiveRecord::Base

mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
  
  def redirect
    redirect_to "/calendar/"
  end
end

app/controllers/eventful_controller.rb
class EventfulController < ApplicationController

	def index
	end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	#writes landing page within Pics webpage
	def index
		@pics = Pic.all
	end

#writes new form for user to upload data (comments, prices, etc.)
	def new
	@pic = Pic.new
	end

#creates new block of data, and redirects user somewhere
	def create
		Pic.create( pic_params )
		redirect_to pics_path
	end

#this is data (Does not come from console)
	private

#when you push save button, permits only blocks in parantheses to be uploaded to database
	def pic_params
	params.require(:pic).permit(:title, 
		:message, :who, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/eventful_helper.rb
module EventfulHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/eventful/index.html.erb
<div class= "span4 offset4 ice-box text-center">

	<h1 class = "awesome-sauce">
	The New Way to Experience Travel.<br> 
	</h1>

	<h2>
		 <br/>Don't believe us?
	</h2>

	<br/>
<%= button_to "Let\'s Get Started!", eventful_next_path, :class => "btn btn-info", :method => :get  %>




</div>

app/views/eventful/next.html.erb
<div class= "span4 offset4 ice-box text-center">

	<h1 class = "awesome-sauce">
	Three Cheers to Free Time!<br>  
	</h1>

	<h2>
		So, what are you interested in?
	</h2>
<form class="form-search">
<input type="text" class="input-medium search-query">
	<h2>
	When are you free?
	</h2>
  <h2>
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen"
     href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css">
  </h2>

 <body>
 	   <h2>From:</h2> <div id="datetimepicker4" class="input-append date">
      <input type="text"></input>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>
    <script type="text/javascript"
     src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script> 
    <script type="text/javascript"
     src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js">
    </script>
    <script type="text/javascript">
      $('#datetimepicker4').datetimepicker({
        format: 'MM/dd/yyyy',
        language: 'en'
      });
    </script>
</body>

 <h2>
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen"
     href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css">
  </h2>

 <body>
 	   <h2>Till:</h2> <div id="datetimepicker2" class="input-append date">
      <input type="text"></input>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>
    <script type="text/javascript"
     src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script> 
    <script type="text/javascript"
     src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js">
    </script>
    <script type="text/javascript">
      $('#datetimepicker2').datetimepicker({
        format: 'MM/dd/yyyy',
        language: 'en'
      });
    </script>
</body>
<!--<form class="form-search">
<input type="text" class="input-medium search-query">
-->
	<h2>
Filter By Price Interval:
	</h2>
<!--<form class="form-search">
<input type="text" class="input-medium search-query">
-->
<%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "$100-$500") %><br>
<%= radio_button_tag(:age, "teen") %>
<%= label_tag(:age_teen, "$501-$1000") %><br>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "$1001-$1500") %><br>
<%= radio_button_tag(:age, "boss") %>
<%= label_tag(:age_boss, "$1501-$2000") %><br>




</form><%= button_to "Let\'s Go!", pics_path, :class => "btn btn-info", :method => :get  %>

</div>

app/views/eventful/test.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen"
     href="http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css">
  </head>
  <body>
    <div id="datetimepicker" class="input-append date">
      <input type="text"></input>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
      </span>
    </div>
    <script type="text/javascript"
     src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
    </script> 
    <script type="text/javascript"
     src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js">
    </script>
    <script type="text/javascript"
     src="http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js">
    </script>
    <script type="text/javascript">
      $('#datetimepicker').datetimepicker({
        format: 'dd/MM/yyyy',
        language: 'en'
      });
    </script>
  </body>
<html>

app/views/layouts/application.html.erb
<!--This is the overall layout of the website
    This consists of tab bars, links, and icons
-->

<!DOCTYPE html>
<html>
<head>
  <title>Eventful. The Pinterest of Travel.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%=  link_to 'Go Home', root_path, 
      :class =>'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      <ul class = "nav">
          <li>
            <%= link_to 'My Interests', pics_path %>
          </li>
          <li>
          <%= link_to 'Post Your Pics!', new_pic_path %>
          </li>

      </ul>
      

      </div>
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Reenie+Beanie&subset=latin' rel='stylesheet' type='text/css'>

	<% @pics.each do |pic| %>
	<div class="span3 text-center">
	<ul id = "notes">
	<li>
		<p>
		<%= pic.title %>
</p>
<p>
		<%= pic.message %>
</p>
	<p>
		<%= pic.who %>
	</p>

	<%= image_tag pic.image %>
	</li>
	</ul>

</form><%= button_to "Let\'s Go!", pics_path, :class => "btn btn-info", :method => :get  %>

	</div>
	<% end %>

app/views/pics/new.html.erb
<div class ="ice-box span6 offset3 text-center">
	<h1 class="awesome sauce">
	Share your Events!
	<h1>
<br/>

	<%= simple_form_for @pic do |f| %>
		<%= f.input :title, label: 'Enter Your Title' , placeholder: 'Wine Bike Tour' %>
		<%= f.input :message, label: 'Where is this happening??', placeholder: 'Upstate New York' %>
		<%= f.input :who, label: 'Who is this?', placeholder: 'e.g. Jay-Z' %>
		<br/>
		<%= f.input :image, label: 'Upload Your Photos'	 %>
		<br/>
		<%= f.submit "Save", :class => 'btn btn-success btn-large' %>
	<%end%>
</div>